name: user_repository
description: "to handle user repository."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  # sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
